name: Compilar para cPanel
on: [workflow_dispatch]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Limpiar y Descargar Código Oficial
        run: |
          # Forzamos la descarga en una subcarpeta para evitar conflictos
          git clone https://github.com/EvolutionAPI/evolution-api.git source_code
          echo "Código descargado en la carpeta source_code"

      - name: 2. Configurar Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: 3. Instalar y Compilar
        run: |
          cd source_code
          npm install
          
          # Buscamos el schema y generamos la base de datos
          SCHEMA_PATH=$(find . -name "schema.prisma")
          echo "Schema encontrado en: $SCHEMA_PATH"
          npx prisma generate --schema=$SCHEMA_PATH
          
          # Compilamos
          npm run build
          
          # Creamos el ZIP desde adentro de la carpeta
          zip -r ../dist.zip dist package.json package-lock.json $(dirname $SCHEMA_PATH)

      - name: 4. Subir Archivo Final
        uses: actions/upload-artifact@v4
        with:
          name: evolucion-api-listo
          path: dist.zip
